name: Frontend Unit Tests

on:
  push:
    branches: [ "main", "test_cicd", "staging" ]
    paths:
      - 'spotify-frontend/**'
  pull_request:
    branches: [ "main", "test_cicd", "staging" ]
    paths:
      - 'spotify-frontend/**'

jobs:
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: spotify-frontend/package-lock.json

      - name: Install Dependencies
        working-directory: ./spotify-frontend
        run: npm ci

      - name: Run Frontend Tests
        working-directory: ./spotify-frontend
        run: npm test
